### ISSUE TITLE
Logo for Open Police

### ISSUE THREAD

**Issue by robinpoort** [belgianpolice/www.openpolice.be#30]
Logo for Open Police.

**Comment by robinpoort** [comment]
[open-police-platform-logo-proposition.pdf](https://github.com/belgianpolice/www.openpolice.be/files/68676/open-police-platform-logo-proposition.pdf)

**Comment by johanjanssens** [comment]
@robinpoort Good work, I like the first one a lot and the idea behind it.

**Comment by robinpoort** [comment]
SVG files have been added to Drive:
Team>Artwork>OpenPolice>Logo

The color has been changed to the openpolice.be logo color.

@tomjanssens Can we close this?

**Comment by tomjanssens** [comment]
@robinpoort can you also add a white version of the logo and avatar?

I also moved the resources to Team > Clients > Belgian Police > Artwork > Logo

**Comment by robinpoort** [comment]
@tomjanssens Done

**Comment by tomjanssens** [comment]
I changed the alignment of 'by Timble' to the bottom right corner.

If you agree with the change can you apply it to the SVG files in Drive?

**Comment by robinpoort** [comment]
Agreed and done

**Comment by tomjanssens** [comment]
Awesome, closing the ticket.
